from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any

import sympy as sp

from .safe_math import exact_value, parse_expr


DOMAIN_ATLAS: dict[str, tuple[str, ...]] = {
    "algebra": ("expand", "factor", "cancel", "together", "apart", "groebner"),
    "polynomials": ("Poly", "factor_list", "resultant", "discriminant", "interpolate"),
    "calculus": ("diff", "integrate", "limit", "series", "summation"),
    "trigonometry": ("trigsimp", "expand_trig", "fu"),
    "number_theory": ("factorint", "totient", "divisors", "isprime", "prime"),
    "linear_algebra": ("Matrix", "det", "inv", "eigenvals", "rank"),
    "combinatorics": ("binomial", "factorial", "fibonacci", "bell"),
    "equations": ("solve", "solveset", "linsolve", "nonlinsolve"),
    "inequalities": ("solve_univariate_inequality", "reduce_inequalities"),
    "sequences": ("summation", "product", "rsolve", "interpolate"),
    "special_functions": ("gamma", "zeta", "erf", "besselj"),
    "geometry": ("Point", "Line", "Circle", "Polygon"),
    "probability": ("stats", "Expectation", "variance"),
    "discrete_math": ("logic", "sets", "combinatorics", "ntheory"),
    "optimization": ("diff", "hessian", "solve", "nsolve"),
}


@dataclass(frozen=True)
class MathLabResult:
    ok: bool
    domain: str
    operation: str
    result: Any
    verification: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "domain": self.domain,
            "operation": self.operation,
            "result": self.result,
            "verification": self.verification,
        }


class SymPyMathLab:
    """Deterministic symbolic-mathematics laboratory.

    SymPy is treated as a computation engine, not as an infallible oracle.
    Operations use domain-specific transformations and each returned result
    includes an explicit verification route where one is available.
    """

    def manifest(self) -> dict[str, Any]:
        return {
            "sympy_version": sp.__version__,
            "domains": {name: list(ops) for name, ops in DOMAIN_ATLAS.items()},
            "domain_count": len(DOMAIN_ATLAS),
            "policy": "specific symbolic transforms are preferred over generic simplify",
        }

    def algebra_normal_forms(self, text: str) -> MathLabResult:
        expr = parse_expr(text)
        expanded = sp.expand(expr)
        factored = sp.factor(expanded)
        together = sp.together(expr)
        cancel = sp.cancel(together)
        exact = (
            sp.expand(expr - expanded) == 0
            and sp.expand(expr - factored) == 0
            and sp.cancel(expr - cancel) == 0
        )
        return MathLabResult(
            ok=bool(exact),
            domain="algebra",
            operation="normal_forms",
            result={
                "input": str(expr),
                "expanded": str(expanded),
                "factored": str(factored),
                "together": str(together),
                "cancelled": str(cancel),
            },
            verification={"exact_symbolic_equivalence": bool(exact)},
        )

    def derivative(self, text: str, variable: str = "x") -> MathLabResult:
        expr = parse_expr(text)
        symbol = next((s for s in expr.free_symbols if s.name == variable), sp.Symbol(variable, real=True))
        derivative = sp.diff(expr, symbol)
        # Independent numerical finite-difference sanity check. This is not a proof;
        # the exact result itself is generated by SymPy's differentiation rules.
        checks = []
        fn = sp.lambdify(symbol, expr, modules=["math"])
        dfn = sp.lambdify(symbol, derivative, modules=["math"])
        for value in (-2.0, -0.75, 0.5, 1.75):
            try:
                h = 1e-6
                numerical = (fn(value + h) - fn(value - h)) / (2.0 * h)
                symbolic = dfn(value)
                checks.append(abs(float(numerical) - float(symbolic)) <= 1e-4 * (1.0 + abs(float(symbolic))))
            except Exception:
                continue
        ok = bool(checks) and all(checks)
        return MathLabResult(
            ok=ok,
            domain="calculus",
            operation="differentiate",
            result={"expression": str(expr), "variable": symbol.name, "derivative": str(derivative)},
            verification={"rule_engine": "sympy.diff", "finite_difference_checks": len(checks), "all_checks": ok},
        )

    def antiderivative(self, text: str, variable: str = "x") -> MathLabResult:
        expr = parse_expr(text)
        symbol = next((s for s in expr.free_symbols if s.name == variable), sp.Symbol(variable, real=True))
        anti = sp.integrate(expr, symbol)
        verified = sp.simplify(sp.diff(anti, symbol) - expr) == 0
        return MathLabResult(
            ok=bool(verified),
            domain="calculus",
            operation="integrate_and_differentiate_back",
            result={"expression": str(expr), "variable": symbol.name, "antiderivative": str(anti)},
            verification={"differentiate_back_exact": bool(verified)},
        )

    def trig_normal_form(self, text: str) -> MathLabResult:
        expr = parse_expr(text)
        transformed = sp.trigsimp(sp.expand_trig(expr))
        # Check equivalence using a symbolic subtraction plus exact high precision
        # evaluations at several rational points.
        symbolic = sp.trigsimp(expr - transformed) == 0
        points_ok = True
        symbols = sorted(expr.free_symbols, key=lambda s: s.name)
        if len(symbols) == 1:
            sym = symbols[0]
            for q in (sp.Rational(1, 7), sp.Rational(2, 5), sp.Rational(5, 6)):
                try:
                    delta = sp.N((expr - transformed).subs(sym, q), 50)
                    points_ok = points_ok and abs(complex(delta)) < 1e-30
                except Exception:
                    points_ok = False
        return MathLabResult(
            ok=bool(symbolic and points_ok),
            domain="trigonometry",
            operation="trig_normal_form",
            result={"input": str(expr), "normal_form": str(transformed)},
            verification={"symbolic_zero": bool(symbolic), "high_precision_points": bool(points_ok)},
        )

    def matrix_invariants(self, rows: list[list[int | float]]) -> MathLabResult:
        matrix = sp.Matrix(rows)
        det = sp.simplify(matrix.det()) if matrix.rows == matrix.cols else None
        rank = int(matrix.rank())
        verification: dict[str, Any] = {"rank_bounds": 0 <= rank <= min(matrix.rows, matrix.cols)}
        if matrix.rows == matrix.cols and det not in (None, 0):
            inv = matrix.inv()
            verification["inverse_identity"] = bool(matrix * inv == sp.eye(matrix.rows))
        else:
            inv = None
        ok = all(bool(v) for v in verification.values())
        return MathLabResult(
            ok=ok,
            domain="linear_algebra",
            operation="matrix_invariants",
            result={
                "shape": [matrix.rows, matrix.cols],
                "determinant": None if det is None else str(det),
                "rank": rank,
                "inverse": None if inv is None else [[str(x) for x in row] for row in inv.tolist()],
            },
            verification=verification,
        )

    def number_theory_profile(self, value: int) -> MathLabResult:
        n = int(value)
        if abs(n) > 10**12:
            raise ValueError("integer is outside bounded v1 number-theory profile")
        target = abs(n)
        factors = sp.factorint(target) if target > 1 else {}
        reconstructed = 1
        for prime, power in factors.items():
            reconstructed *= int(prime) ** int(power)
        divisors = sp.divisors(target) if 0 < target <= 10**6 else []
        verified = target in (0, 1) or reconstructed == target
        if divisors:
            verified = verified and all(target % int(d) == 0 for d in divisors)
        return MathLabResult(
            ok=bool(verified),
            domain="number_theory",
            operation="factor_profile",
            result={
                "n": n,
                "is_prime": bool(sp.isprime(target)),
                "factorization": {str(k): int(v) for k, v in factors.items()},
                "totient": None if target == 0 else int(sp.totient(target)),
                "divisors": [int(x) for x in divisors[:1000]],
            },
            verification={"reconstructed_exactly": bool(verified)},
        )

    def polynomial_interpolate(self, points: list[tuple[int, int]], variable: str = "n") -> MathLabResult:
        if len(points) < 2 or len(points) > 20:
            raise ValueError("interpolation requires 2..20 exact points")
        n = sp.Symbol(variable, integer=True, nonnegative=True)
        poly = sp.interpolate([(sp.Integer(x), sp.Integer(y)) for x, y in points], n)
        checks = [sp.expand(poly.subs(n, x) - y) == 0 for x, y in points]
        return MathLabResult(
            ok=all(checks),
            domain="polynomials",
            operation="interpolate",
            result={"polynomial": str(sp.factor(poly)), "expanded": str(sp.expand(poly))},
            verification={"all_input_points_exact": all(checks), "points": len(points)},
        )

    def domain_probe(self, domain: str) -> MathLabResult:
        """Run a deterministic, domain-specific capability probe.

        The architecture benchmark calls this instead of rewarding an expert
        merely because its name appears in the genome.
        """
        domain = str(domain)
        if domain not in DOMAIN_ATLAS:
            raise ValueError(f"unknown mathematical domain: {domain}")

        if domain == "algebra":
            return self.algebra_normal_forms("(x+1)^4-(x^4+4*x^3+6*x^2+4*x+1)")
        if domain == "polynomials":
            return self.polynomial_interpolate([(0, 1), (1, 4), (2, 9), (3, 16)])
        if domain == "calculus":
            derivative = self.derivative("x^4+2*x")
            antiderivative = self.antiderivative("3*x^2")
            checks = {
                "derivative": derivative.ok,
                "antiderivative": antiderivative.ok,
            }
        elif domain == "trigonometry":
            return self.trig_normal_form("sin(x)^2+cos(x)^2")
        elif domain == "number_theory":
            return self.number_theory_profile(360)
        elif domain == "linear_algebra":
            return self.matrix_invariants([[2, 1], [1, 1]])
        elif domain == "combinatorics":
            checks = {
                "binomial": sp.binomial(8, 3) == 56,
                "factorial": sp.factorial(6) == 720,
                "fibonacci": sp.fibonacci(10) == 55,
            }
        elif domain == "equations":
            x = sp.Symbol("x", real=True)
            solutions = set(sp.solve(sp.Eq(x**2 - 5*x + 6, 0), x))
            checks = {"exact_solution_set": solutions == {sp.Integer(2), sp.Integer(3)}}
        elif domain == "inequalities":
            x = sp.Symbol("x", real=True)
            reduced = sp.reduce_inequalities([x**2 >= 0], x)
            checks = {"universal_nonnegative_square": bool(reduced == sp.true)}
        elif domain == "sequences":
            k = sp.Symbol("k", integer=True, positive=True)
            n = sp.Symbol("n", integer=True, nonnegative=True)
            total = sp.summation(k, (k, 1, n))
            product = sp.product(k, (k, 1, 5))
            checks = {
                "symbolic_sum": sp.simplify(total - n * (n + 1) / 2) == 0,
                "finite_product": product == 120,
            }
        elif domain == "special_functions":
            checks = {
                "gamma": sp.gamma(6) == 120,
                "zeta": sp.simplify(sp.zeta(2) - sp.pi**2 / 6) == 0,
                "erf": sp.erf(0) == 0,
                "bessel": sp.besselj(0, 0) == 1,
            }
        elif domain == "geometry":
            from sympy.geometry import Line, Point

            p0 = Point(0, 0)
            p1 = Point(3, 4)
            diagonal_a = Line(Point(0, 0), Point(1, 1))
            diagonal_b = Line(Point(0, 1), Point(1, 0))
            checks = {
                "exact_distance": p0.distance(p1) == 5,
                "line_intersection": diagonal_a.intersection(diagonal_b) == [Point(sp.Rational(1, 2), sp.Rational(1, 2))],
            }
        elif domain == "probability":
            from sympy.stats import Die, E, variance

            die = Die("mathesis_probe_die", 6)
            checks = {
                "expectation": sp.simplify(E(die) - sp.Rational(7, 2)) == 0,
                "variance": sp.simplify(variance(die) - sp.Rational(35, 12)) == 0,
            }
        elif domain == "discrete_math":
            p, q = sp.symbols("p q", boolean=True)
            implication = sp.Implies(p, q)
            checks = {
                "logic_equivalence": sp.simplify_logic(sp.Equivalent(implication, sp.Or(sp.Not(p), q))) == sp.true,
                "finite_sets": sp.FiniteSet(1, 2, 3).intersection(sp.FiniteSet(2, 3, 4)) == sp.FiniteSet(2, 3),
            }
        elif domain == "optimization":
            x, y = sp.symbols("x y", real=True)
            objective = (x - 3) ** 2 + (y + 2) ** 2
            gradient = [sp.diff(objective, v) for v in (x, y)]
            stationary = sp.solve(gradient, (x, y), dict=True)
            checks = {
                "stationary_point": stationary == [{x: 3, y: -2}],
                "positive_hessian": sp.hessian(objective, (x, y)) == sp.diag(2, 2),
            }
        else:  # pragma: no cover - DOMAIN_ATLAS additions must add a probe.
            raise AssertionError(f"DOMAIN_ATLAS domain lacks a probe: {domain}")

        ok = all(bool(value) for value in checks.values())
        return MathLabResult(
            ok=ok,
            domain=domain,
            operation="domain_probe",
            result={"checks": {name: bool(value) for name, value in checks.items()}},
            verification={"all_domain_checks": ok, **{name: bool(value) for name, value in checks.items()}},
        )

