"""Generated MATHESIS-Ω architecture model.

This file is data-bearing executable Python with no imports/calls. It is generated transactionally and never replaces the verifier kernel.
"""

MODEL = {'counterexample_radius': 9,
 'discovery_beam': 8,
 'experts': ['formalization',
             'algebra',
             'counterexample',
             'program_synthesis',
             'number_theory',
             'research',
             'calculus',
             'trigonometry',
             'sequences',
             'linear_algebra',
             'equations',
             'inequalities',
             'special_functions',
             'geometry',
             'probability',
             'discrete_math',
             'optimization',
             'combinatorics'],
 'generation': 14,
 'genome_id': 'omega-14-bb784c03',
 'max_proof_cells': 224,
 'neural_hidden': 20,
 'parent_id': 'omega-13-f6ddf2ac',
 'proof_order': ['symbolic', 'smt', 'counterexample', 'lean'],
 'research_budget': 3,
 'strategy_portfolio': ['exact_symbolic',
                        'smt_validity',
                        'counterexample',
                        'lean',
                        'conjecture_discovery',
                        'specific_normal_forms',
                        'finite_difference',
                        'exact_sampling',
                        'read_only_research'],
 'symbolic_depth': 12,
 'topology': [('formalization', 'algebra'),
              ('algebra', 'counterexample'),
              ('counterexample', 'program_synthesis'),
              ('program_synthesis', 'number_theory'),
              ('number_theory', 'research'),
              ('research', 'calculus'),
              ('calculus', 'trigonometry'),
              ('trigonometry', 'sequences'),
              ('sequences', 'linear_algebra'),
              ('linear_algebra', 'equations'),
              ('equations', 'inequalities'),
              ('inequalities', 'special_functions'),
              ('special_functions', 'geometry'),
              ('geometry', 'probability'),
              ('probability', 'discrete_math'),
              ('discrete_math', 'optimization'),
              ('optimization', 'combinatorics'),
              ('program_synthesis', 'counterexample'),
              ('number_theory', 'counterexample'),
              ('research', 'counterexample'),
              ('calculus', 'counterexample'),
              ('trigonometry', 'counterexample'),
              ('sequences', 'counterexample'),
              ('linear_algebra', 'counterexample'),
              ('equations', 'counterexample'),
              ('inequalities', 'counterexample'),
              ('special_functions', 'counterexample'),
              ('geometry', 'counterexample'),
              ('probability', 'counterexample'),
              ('discrete_math', 'counterexample'),
              ('optimization', 'counterexample'),
              ('combinatorics', 'counterexample')]}
